import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Eye, Lightbulb, Pencil, RotateCcw } from 'lucide-react';
import { draftKey, useLab } from '../store';
import { constraintsFor, contrastingExamples } from '../learningContent';
import type { Tab, Value } from '../types';
import { display } from './Visualizer';
import DiscoveryExperiment from './DiscoveryExperiment';

type Notes = { discoveryAnswer?: string; discoveryStep?: string; discoveryAnswers?: Record<number, string>; assumptions?: string; decision?: string; counterexample?: string; prediction?: string; plan?: string; technique?: string; rationale?: string; reasoning?: string; mistake?: string; time?: string; space?: string; adaptation?: string; recall?: Record<number, string>; transferFrom?: string; transferPlan?: string };
function readNotes(key: string): Notes {
  try { const value = JSON.parse(localStorage.getItem(key) || '{}'); return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; } catch { return {}; }
}

export default function LearningPanel({ onExplore, onChoose }: { onExplore: () => void; onChoose: (id: string, tab?: Tab) => void }) {
  const { problem: p, tab, setTab, hints, hint, hintContext, stage, run, runCode, code, source, problems } = useLab();
  const noteKey = draftKey(p?.id || '') + ':learning-notes';
  const [notes, setNotes] = useState<Notes>(() => readNotes(noteKey));
  const [saved, setSaved] = useState('Notes stay on this device.');
  const [exampleIndex, setExampleIndex] = useState(0);
  const [showOutput, setShowOutput] = useState(false);
  const [selected, setSelected] = useState<{ param: number; index: number } | null>(null);
  const [discovery, setDiscovery] = useState(Number(notes.discoveryStep) || 0);
  const [clues, setClues] = useState<number[]>([]);
  const [feedback, setFeedback] = useState('');
  const [revealComplexity, setRevealComplexity] = useState(false);
  const update = (patch: Partial<Notes>) => {
    const next = { ...notes, ...patch }; setNotes(next);
    try { localStorage.setItem(noteKey, JSON.stringify(next)); setSaved('Notes saved on this device.'); } catch { setSaved('Device storage is unavailable. Keep this page open to retain your notes.'); }
  };
  if (!p) return null;
  const related = problems.find(q => q.id === p.transfer);
  const example = exampleIndex === 1 ? contrastingExamples[p.id] || p.example : p.example;
  const explanation = 'why' in example ? String(example.why) : p.id === 'two-sum' ? '2 + 7 = 9. The answer [0,1] contains their positions, not their values.' : p.decoder.find + ' ' + p.decoder.returns;
  const selectedValue = selected ? (example.args[selected.param] as Value[] | string)?.[selected.index] : undefined;
  const stale = !!run && runCode !== code;
  const tested = !!run && !run.preview && source === 'mine' && !stale;
  const next = (target: Tab) => setTab(target);
  const moveDiscovery = (index: number) => { setDiscovery(index); update({ discoveryStep: String(index), discoveryAnswer: notes.discoveryAnswers?.[index] || '' }); };
  const noteField = (label: string, field: keyof Omit<Notes, 'recall' | 'discoveryAnswers'>, placeholder: string, rows = 3) => <label className="journey-field"><span>{label}</span><textarea value={notes[field] || ''} onChange={e => update({ [field]: e.target.value })} placeholder={placeholder} rows={rows} maxLength={6000}/></label>;

  return <div className={`learning-panel lesson-stage-${tab}`}>
    {tab === 'understand' && <>
      <div className="stage-intro"><span className="stage-badge"><BookOpen size={18}/> 01 / MAKE SENSE OF IT</span><h2>Understand the question.</h2><p>Explore what goes in, what comes out, and the rules connecting them.</p></div>
      <div className="understand-contract">{[['Input', p.decoder.given], ['Goal', p.decoder.find], ['Output', p.decoder.returns]].map(([title, text], i) => <div key={title}><span>0{i + 1} / {title}</span><p>{text}</p></div>)}</div>
      <div className="understand-grid"><section className="lesson-card example-lab" aria-label="Visual example explorer"><div className="lesson-card-heading"><h3>Make the example tangible.</h3><div className="example-switch">{['Example 1', 'Example 2'].map((label, i) => <button key={label} aria-pressed={exampleIndex === i} onClick={() => { setExampleIndex(i); setSelected(null); setShowOutput(false); }}>{label}</button>)}</div></div>
        {p.params.map((name, param) => <div className="example-parameter" key={name}><span className="tiny-label">{name}</span>{Array.isArray(example.args[param]) || typeof example.args[param] === 'string' ? <div className="intuition-cells">{Array.from(example.args[param] as Value[]).map((value, index) => <button key={index} className={selected?.param === param && selected.index === index ? 'selected' : ''} aria-label={`${name} index ${index}: ${display(value)}`} onClick={() => setSelected({ param, index })}><small>{index}</small><strong>{value === ' ' ? '␣' : display(value)}</strong></button>)}{!(example.args[param] as Value[] | string).length && <span className="small">Empty sequence · no positions</span>}</div> : <code className="example-scalar">{display(example.args[param])}</code>}</div>)}
        <p className="intuition-note" role="status">{selected ? <>{p.params[selected.param]} at position <b>{selected.index}</b> holds <b>{display(selectedValue ?? null)}</b>. A position and its value are different things.</> : 'Select an element to explore its position and value. This is an input illustration, not a code execution.'}</p>
        {noteField('Predict the output', 'prediction', 'Before revealing the result, what should this example return?', 2)}
        <button className="outline-button" onClick={() => setShowOutput(!showOutput)}><Eye size={15}/>{showOutput ? 'Hide expected output' : 'Reveal expected output'}</button>
        {showOutput && <div className="example-answer"><span className="tiny-label">EXPECTED OUTPUT</span><code>{display(example.expected)}</code><p>{explanation}</p></div>}
      </section><aside className="lesson-card constraint-card"><span className="tiny-label">THE CONTRACT</span><h3>What must stay true?</h3><ul>{constraintsFor(p).map(rule => <li key={rule}>{rule}</li>)}</ul><div className="think-prompt"><Lightbulb size={18}/><p>What would the smallest valid input look like? What changes when values repeat?</p></div></aside></div>
      <div className="stage-next"><span>Can you describe the goal without choosing an algorithm?</span><button className="primary-button" onClick={() => { void stage('Understood'); next('discover'); }}>Continue to Discover<ArrowRight size={16}/></button></div>
    </>}

    {tab === 'discover' && <>
      <div className="stage-intro"><span className="stage-badge"><Lightbulb size={18}/> 02 / FIND THE APPROACH</span><h2>Reason before you write.</h2><p>Start with an obvious idea. Find the repeated work. Decide what information helps.</p></div>
      <div className="reasoning-workspace"><section className="reasoning-path" aria-label="Approach discovery"><div className="reasoning-rail">{['Brute force', 'Bottleneck', 'Key observation', 'Optimization'].map((label, i) => <button key={label} aria-pressed={discovery === i} className={discovery === i ? 'selected' : ''} onClick={() => moveDiscovery(i)}><span>0{i + 1}</span>{label}<ChevronRight size={14}/></button>)}</div><article className="reasoning-observation"><span className="tiny-label">OBSERVATION {discovery + 1} / 4</span><h3>{['What is the simplest correct idea?', 'Where are you repeating work?', 'What information is missing?', 'How can you reuse what you know?'][discovery]}</h3><label className="journey-field"><span>Your reasoning at this step</span><textarea rows={3} maxLength={2000} placeholder={['What would you try first on the example?', 'Which operation happens again and again?', 'What could you remember from earlier work?', 'What must remain true as your approach advances?'][discovery]} value={notes.discoveryAnswers?.[discovery] || ''} onChange={e => update({ discoveryAnswer: e.target.value, discoveryAnswers: { ...notes.discoveryAnswers, [discovery]: e.target.value } })}/></label>{clues.includes(discovery) ? <div className="discovery-clue"><span className="tiny-label">COMPARE YOUR OBSERVATION</span><p>{p.discovery[discovery]}</p></div> : <button className="outline-button" onClick={() => setClues(rows => [...rows, discovery])}>Reveal a reasoning prompt</button>}<button className="text-button" onClick={() => moveDiscovery((discovery + 1) % 4)}>{discovery === 3 ? 'Revisit the simple idea' : 'Next observation'}<ArrowRight size={15}/></button></article></section>
      <section className="lesson-card approach-notebook" aria-label="Approach notebook"><div className="lesson-card-heading"><h3>Your approach notebook</h3><span className="tiny-label">PSEUDOCODE · NOT EXECUTED</span></div><label className="journey-field"><span>Choose a technique to investigate</span><select value={notes.technique || ''} onChange={e => update({ technique: e.target.value })}><option value="">Choose your hypothesis…</option>{['Direct iteration / brute force', 'Hash map / set', 'Two pointers', 'Sliding window', 'Binary search', 'Running best / running total'].map(t => <option key={t}>{t}</option>)}</select></label>{noteField('Why might this technique help?', 'rationale', 'Which repeated work could it remove? What assumptions does it need?', 2)}{noteField('Write the steps in your own words', 'plan', '1. Keep track of…\n2. For each…\n3. If…\n4. Return…', 7)}<p className="notebook-status">{saved}</p></section></div>
      <DiscoveryExperiment problem={p} phase={discovery}/>
      <div className="stage-next"><button className="text-button" onClick={() => next('understand')}><ArrowLeft size={15}/> Revisit the problem</button><button className="primary-button" onClick={() => next('code')}>Take my approach to code<ArrowRight size={16}/></button></div>
    </>}

    {tab === 'code' && <><div className="stage-intro code-stage-intro"><span className="stage-badge"><Pencil size={18}/> 03 / TEST YOUR THINKING</span><h2>Make your idea executable.</h2><p>Your program determines every state and step below—even when its behavior is incorrect.</p><button className="text-button" onClick={onExplore}>Study a reference approach<ArrowRight size={14}/></button></div>{(notes.plan || notes.transferPlan) && <details className="approach-carry" open><summary>{notes.transferFrom ? `Adaptation from ${notes.transferFrom}` : 'Your approach from Discover'}</summary>{notes.technique && <span>{notes.technique}</span>}<pre>{notes.transferPlan || notes.plan}</pre><button className="text-button" onClick={() => next('discover')}>Revise the reasoning<ArrowLeft size={13}/></button></details>}</>}

    {tab === 'reflect' && <>
      <div className="stage-intro"><span className="stage-badge"><RotateCcw size={18}/> 04 / MAKE IT YOURS</span><h2>Explain it. Challenge it. Transfer it.</h2><p>Turn the result of an experiment into reasoning you can use again.</p></div>
      <section className="reflection-evidence lesson-card"><span className="tiny-label">YOUR EXPERIMENT</span><h3>{tested ? run!.error ? 'Execution stopped. What assumption broke?' : run!.passed && run!.tests.every(t => t.passed) ? 'Your tests passed. Why does it work?' : 'A mismatch is a clue.' : stale ? 'Your code changed after this trace.' : 'Build evidence for your reasoning.'}</h3>{run ? <><p>{run.preview ? 'Current-input preview' : source !== 'mine' ? 'Reference execution' : 'Latest learner execution'} · returned <code>{display(run.result)}</code>{!run.preview && <> · {run.tests.filter(t => t.passed).length}/{run.tests.length} checks passed</>}</p>{run.error && <p className="evidence-error">{run.error.type}: {run.error.message}</p>}{run.divergence && <p>{run.divergence.message}</p>}{stale && <p>This trace describes earlier code. Run your current draft before using it as evidence.</p>}</> : <p>No execution yet. You can draft your explanation now, then return to Code & Visualize to test it.</p>}<button className="text-button" onClick={() => next('code')}>Revisit Code & Visualize<ArrowRight size={15}/></button></section>
      <div className="reflection-grid"><section className="lesson-card"><h3>Why does your solution work?</h3>{noteField('Your invariant or correctness argument', 'reasoning', 'What stays true after each step? Why does that guarantee the required result?', 4)}{noteField('Which assumption does your approach rely on?', 'assumptions', 'Sorted input? Distinct positions? Contiguous ranges? Why is this needed?', 2)}{noteField('Defend one important decision', 'decision', 'Why this data structure or boundary update instead of another?', 2)}{noteField('Mistake → lesson', 'mistake', 'What did you expect? What actually happened? Which assumption did you change?', 3)}<div className="complexity-estimates">{noteField('Time growth', 'time', 'e.g. O(n), because…', 2)}{noteField('Extra space', 'space', 'What grows with the input?', 2)}</div><button className="text-button" onClick={() => setRevealComplexity(!revealComplexity)}>{revealComplexity ? 'Hide reference complexity' : 'Compare with reference complexity'}<Eye size={14}/></button>{revealComplexity && <p className="complexity-reference">Authored optimized approach: <b>{p.complexity.time}</b> time, <b>{p.complexity.space}</b> space. This is not a measurement of your draft. Explain any difference.</p>}<button className="outline-button save-reflection" disabled={(notes.reasoning || '').trim().length < 40} onClick={async () => { useLab.getState().clearError(); await stage('Explained', JSON.stringify({ reasoning: notes.reasoning, mistake: notes.mistake, time: notes.time, space: notes.space, recall: notes.recall })); setFeedback(useLab.getState().error ? 'Could not save progress. Local notes are retained; try again.' : 'Reflection saved. This records your explanation, not an automated judgment of mastery.'); }}><Check size={15}/> Save reflection</button>{feedback && <p className="small" role="status">{feedback}</p>}</section>
      <section className="lesson-card recall-card"><span className="tiny-label">ACTIVE RECALL</span><h3>Close the code. Retrieve the idea.</h3>{p.recall.map((question, i) => <label className="journey-field" key={question}><span><b>0{i + 1}</b> {question}</span><textarea rows={3} maxLength={2000} placeholder="Explain from memory…" value={notes.recall?.[i] || ''} onChange={e => update({ recall: { ...notes.recall, [i]: e.target.value } })}/></label>)}{noteField('Try to break your own reasoning', 'counterexample', 'If input size grows 10× or an assumption changes, give an input that challenges your approach. What would you test?', 3)}<p className="notebook-status">{saved}</p></section></div>
      {related && <section className="transfer-workshop lesson-card"><div><span className="tiny-label">TRANSFER CHALLENGE</span><h3>{p.title} <ArrowRight size={22}/> {related.title}</h3><p>Read the changed contract before adapting your code.</p><div className="transfer-contracts"><div><span>THIS PROBLEM</span><p>{p.statement}</p></div><div><span>THE VARIATION</span><p>{related.statement}</p><code>Example: {related.example.args.map(display).join(' · ')} → {display(related.example.expected)}</code></div></div></div><div>{noteField('What will you keep, and what must change?', 'adaptation', 'Name the changed assumption and describe the code you will adapt.', 4)}<button className="primary-button" disabled={(notes.adaptation || '').trim().length < 20} onClick={() => { const key = draftKey(related.id) + ':learning-notes'; try { localStorage.setItem(key, JSON.stringify({ ...readNotes(key), transferFrom: p.title, transferPlan: notes.adaptation })); } catch { setFeedback('Could not carry the plan to the new problem. Copy your notes before continuing.'); return; } onChoose(related.id, 'code'); }}>Open variation & adapt code<ArrowRight size={15}/></button><p className="small">Write a short adaptation plan to continue. Your current code is kept; the variation opens its own draft with your plan beside it.</p></div></section>}
    </>}
    {(tab === 'discover' || tab === 'code') && hints > 0 && <details className="journey-hints"><summary><Lightbulb size={15}/> Your guidance · {hints} hint{hints === 1 ? '' : 's'}</summary>{hintContext && <p>{hintContext}</p>}{p.hints.slice(0, hints).map((text, i) => <p key={i}><b>{i + 1}.</b> {text}</p>)}{hints < p.hints.length && <button className="text-button" onClick={() => void hint()}>A little more guidance<ChevronRight size={14}/></button>}</details>}
  </div>;
}
